---
# These tasks install http and the php modules.

# A helpful reminder of what to look out for post-update.
- pause:
    prompt: "Make sure All NGINX+HTTPD is started"

- name: Check that you can connect (GET) to a page and it returns a status 200
  uri:
      url: http://{{ ansible_default_ipv4.address }}

      # Check that a page returns a status 200 and fail if the word DEV is not
      # in the page contents.
- uri:
   url: http://{{ ansible_default_ipv4.address }}
   return_content: yes
  register: webpage

- name: Fail if DEV is not in the page content
  fail:
  when: "'DEV' not in webpage.content"