---
# This playbook contains common plays that will be run on all nodes.

- name: Install ntp
  yum: name=ntp state=present
  tags: ntp

- name: Install libsemanage
  yum: name={{ item }} state=present
  with_items:
  - libsemanage-python
  - libselinux-python
  - policycoreutils-python

- name: Configure ntp file
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  tags: ntp
  notify: restart ntp

- name: Start the ntp service
  service: name=ntpd state=started enabled=yes
  tags: ntp

- name: test to see if selinux is running
  command: getenforce
  register: sestatus
  changed_when: false

- name: Copy the EPEL repository definition
  copy: src=epel.repo dest=/etc/yum.repos.d/epel.repo
  
- name: Create the GPG key for EPEL
  copy: src=RPM-GPG-KEY-EPEL-6 dest=/etc/pki/rpm-gpg
    
#- name: Set up iptables rules
#  copy: src=iptables-save dest=/etc/sysconfig/iptables
#  notify: restart iptables

- name: Config SELinux over Shell httpd_can_network_connect
  shell: 'setsebool -P httpd_can_network_connect 1'

#- name: Config SELinux open_relay 8081 port over Shell
#  shell: 'semanage port -m -t http_port_t -p tcp 8080'

- name: Config SELinux to permissive over Shell
  shell: 'semanage permissive -a httpd_t'
      
#- name: Config SELinux to global permissive over Shell
#  shell: 'setenforce 0'
                