---
- name: Install nginx
  yum: name=nginx state=present

- name: Copy nginx configuration for proxy
  template: src=default.conf dest=/etc/nginx/conf.d/default.conf
  notify: restart nginx

- name: Set up iptables rules
  copy: src=iptables-save dest=/etc/sysconfig/iptables
  notify: restart iptables